# Generated by Django 3.2.4 on 2021-06-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='rating',
            new_name='individual_rating',
        ),
    ]
